<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Club extends \Par3\GolfEnLaNubeBundle\Entity\Club implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdInstitucion($idInstitucion)
    {
        $this->__load();
        return parent::setIdInstitucion($idInstitucion);
    }

    public function getIdInstitucion()
    {
        $this->__load();
        return parent::getIdInstitucion();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setInstitucion(\Par3\GolfEnLaNubeBundle\Entity\Institucion $institucion = NULL)
    {
        $this->__load();
        return parent::setInstitucion($institucion);
    }

    public function getInstitucion()
    {
        $this->__load();
        return parent::getInstitucion();
    }

    public function addCancha(\Par3\GolfEnLaNubeBundle\Entity\Cancha $canchas)
    {
        $this->__load();
        return parent::addCancha($canchas);
    }

    public function removeCancha(\Par3\GolfEnLaNubeBundle\Entity\Cancha $canchas)
    {
        $this->__load();
        return parent::removeCancha($canchas);
    }

    public function getCanchas()
    {
        $this->__load();
        return parent::getCanchas();
    }

    public function tieneCanchaNumero($numero)
    {
        $this->__load();
        return parent::tieneCanchaNumero($numero);
    }

    public function getCanchaNumero($numero)
    {
        $this->__load();
        return parent::getCanchaNumero($numero);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setCodigoAag($codigoAag)
    {
        $this->__load();
        return parent::setCodigoAag($codigoAag);
    }

    public function getCodigoAag()
    {
        $this->__load();
        return parent::getCodigoAag();
    }

    public function setPendienteActualizacion($pendienteActualizacion)
    {
        $this->__load();
        return parent::setPendienteActualizacion($pendienteActualizacion);
    }

    public function getPendienteActualizacion()
    {
        $this->__load();
        return parent::getPendienteActualizacion();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function addTemporadaClub(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClub $temporadaClubs)
    {
        $this->__load();
        return parent::addTemporadaClub($temporadaClubs);
    }

    public function removeTemporadaClub(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClub $temporadaClubs)
    {
        $this->__load();
        return parent::removeTemporadaClub($temporadaClubs);
    }

    public function getTemporadaClubs()
    {
        $this->__load();
        return parent::getTemporadaClubs();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'id_institucion', 'nombre', 'pendiente_actualizacion', 'institucion', 'canchas', 'temporada_clubs');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}