<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Persona extends \Par3\GolfEnLaNubeBundle\Entity\Persona implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdUsuario($idUsuario)
    {
        $this->__load();
        return parent::setIdUsuario($idUsuario);
    }

    public function getIdUsuario()
    {
        $this->__load();
        return parent::getIdUsuario();
    }

    public function setNombreCompleto($nombreCompleto)
    {
        $this->__load();
        return parent::setNombreCompleto($nombreCompleto);
    }

    public function getNombreCompleto()
    {
        $this->__load();
        return parent::getNombreCompleto();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setApellido($apellido)
    {
        $this->__load();
        return parent::setApellido($apellido);
    }

    public function getApellido()
    {
        $this->__load();
        return parent::getApellido();
    }

    public function setSexo($sexo)
    {
        $this->__load();
        return parent::setSexo($sexo);
    }

    public function getSexo()
    {
        $this->__load();
        return parent::getSexo();
    }

    public function setFechaNacimiento($fechaNacimiento)
    {
        $this->__load();
        return parent::setFechaNacimiento($fechaNacimiento);
    }

    public function getFechaNacimiento()
    {
        $this->__load();
        return parent::getFechaNacimiento();
    }

    public function setUsuario(\Par3\GolfEnLaNubeBundle\Entity\User $usuario = NULL)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setJugador(\Par3\GolfEnLaNubeBundle\Entity\Jugador $jugador = NULL)
    {
        $this->__load();
        return parent::setJugador($jugador);
    }

    public function getJugador()
    {
        $this->__load();
        return parent::getJugador();
    }

    public function setTelefonos($telefonos)
    {
        $this->__load();
        return parent::setTelefonos($telefonos);
    }

    public function getTelefonos()
    {
        $this->__load();
        return parent::getTelefonos();
    }

    public function addTelefono($telefono)
    {
        $this->__load();
        return parent::addTelefono($telefono);
    }

    public function removeTelefono($telefono)
    {
        $this->__load();
        return parent::removeTelefono($telefono);
    }

    public function setTipoDocumento($tipoDocumento)
    {
        $this->__load();
        return parent::setTipoDocumento($tipoDocumento);
    }

    public function getTipoDocumento()
    {
        $this->__load();
        return parent::getTipoDocumento();
    }

    public function setNumeroDocumento($numeroDocumento)
    {
        $this->__load();
        return parent::setNumeroDocumento($numeroDocumento);
    }

    public function getNumeroDocumento()
    {
        $this->__load();
        return parent::getNumeroDocumento();
    }

    public function setPendienteActualizacion($pendienteActualizacion)
    {
        $this->__load();
        return parent::setPendienteActualizacion($pendienteActualizacion);
    }

    public function getPendienteActualizacion()
    {
        $this->__load();
        return parent::getPendienteActualizacion();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'id_usuario', 'nombre_completo', 'nombre', 'apellido', 'sexo', 'fecha_nacimiento', 'tipo_documento', 'numero_documento', 'telefonos', 'pendiente_actualizacion', 'usuario', 'jugador');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}