<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Circuito extends \Par3\GolfEnLaNubeBundle\Entity\Circuito implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getInstanciaReglamentoJuego()
    {
        $this->__load();
        return parent::getInstanciaReglamentoJuego();
    }

    public function getClaseReglamentoJuego()
    {
        $this->__load();
        return parent::getClaseReglamentoJuego();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setIdInstitucion($idInstitucion)
    {
        $this->__load();
        return parent::setIdInstitucion($idInstitucion);
    }

    public function getIdInstitucion()
    {
        $this->__load();
        return parent::getIdInstitucion();
    }

    public function setInstitucion(\Par3\GolfEnLaNubeBundle\Entity\Institucion $institucion = NULL)
    {
        $this->__load();
        return parent::setInstitucion($institucion);
    }

    public function getInstitucion()
    {
        $this->__load();
        return parent::getInstitucion();
    }

    public function setSubdominio($subdominio)
    {
        $this->__load();
        return parent::setSubdominio($subdominio);
    }

    public function getSubdominio()
    {
        $this->__load();
        return parent::getSubdominio();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'id_institucion', 'nombre', 'subdominio', 'institucion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}