<?php

namespace Par3\GolfEnLaNubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ClassesWithParents\A;

/**
 * CampeonatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampeonatoRepository extends EntityRepository
{
	
	public function resultadosPorTemporadaClub($id_campeonato)
	{
		$stmt = $this->getEntityManager()
		->getConnection()
		->prepare("select 
					id_temporada_club,
					concat (club.nombre , ' \"', coalesce(concat(tc.equipo_intraclub, '\"'),'\"')) as equipo_nombre,
					sum(e.puntaje_total) as cc_puntaje
					from temporada_club tc
					inner Join club on club.id = tc.id_club
					inner Join equipo e on e.id_temporada_club = tc.id
					inner Join torneo_fecha tf on tf.id = e.id_torneo_fecha 
					inner Join torneo t on t.id = tf.id_torneo
					inner Join torneo_campeonato tco on tco.id_torneo = t.id  
					inner Join campeonato c on c.id = tco.id_campeonato
					where c.id = $id_campeonato
					group by id_temporada_club, equipo_nombre
					order by cc_puntaje DESC");
		// $stmt->bindValue('id_campeonato ', $id_campeonato);
		$stmt->execute();
		return $stmt->fetchAll();
	}

	public function resultadosPorTemporadaClubYFecha($id_campeonato)
	{
		$stmt = $this->getEntityManager()
		->getConnection()
		->prepare("select
			id_temporada_club,
			concat (club.nombre , ' \"', coalesce(concat(tc.equipo_intraclub, '\"'), '\"')) as equipo_nombre,
			t.nombre as nombre_torneo,
			tf.fecha as fecha_torneo,
			e.puntaje_total
			
			from temporada_club tc
			inner Join club on club.id = tc.id_club
			inner Join equipo e on e.id_temporada_club = tc.id
			inner Join torneo_fecha tf on tf.id = e.id_torneo_fecha
			inner Join torneo t on t.id = tf.id_torneo
			inner Join torneo_campeonato tco on tco.id_torneo = t.id
			inner Join campeonato c on c.id = tco.id_campeonato
			where c.id = $id_campeonato
			order by tf.fecha ASC, e.puntaje_total DESC");
				// $stmt->bindValue('id_campeonato ', $id_campeonato);
		$stmt->execute();
		return $stmt->fetchAll();
	}
	
}
