<?php

namespace Par3\GolfEnLaNubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ClassesWithParents\A;

/**
 * CanchaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanchaRepository extends EntityRepository
{
	public function todasCanchasDisponiblesEnTemporada($id_temporada)
	{
		return $this->getEntityManager()->createQuery(
					"SELECT ca 
						FROM GolfEnLaNubeBundle:Cancha ca 
						INNER JOIN ca.club c 
						INNER JOIN c.temporada_clubs tc
					WHERE tc.id_temporada = :id_temporada")
				->setParameter('id_temporada', $id_temporada)
				->execute();
	}
}
