<?php

namespace Par3\GolfEnLaNubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ClassesWithParents\A;
use Doctrine\Common\Util\Debug;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends EntityRepository
{
	/**
	 * 
	 * @param User $usuario_capitan
	 * @param TorneoFecha $torneo_fecha
	 */
	public function equiposDeCapitanEnTorneoFecha(User $usuario_capitan, TorneoFecha $torneo_fecha)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();

		return $qb	->select ('e')
			->from('GolfEnLaNubeBundle:Equipo', 'e')
			->innerJoin('e.torneo_fecha', 'tf')
			->where( 	$qb->expr()->in('e.id_club', $usuario_capitan->getIdClubsCapitaneadosEnTemporada( $torneo_fecha->getTorneo()->getTemporada()->getId()) ) )
			->andWhere('e.id_torneo_fecha = :id_torneo_fecha')
			->setParameter('id_torneo_fecha', $torneo_fecha->getId())
			->getQuery()
			->execute();
	} 
	
}
