<?php

namespace Par3\GolfEnLaNubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ClassesWithParents\A;
use Doctrine\Common\Util\Debug;

/**
 * JugadorActualizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadorActualizacionRepository extends EntityRepository
{

	public function getQueryActualizacionesJugadorOrderByVigenciaDesc($id_jugador)
	{
		return $this->createQueryBuilder('ja')
			->select('ja')
			->where('ja.id_jugador = :jugador')->setParameter('jugador', $id_jugador)
			->orderBy('ja.vigencia', 'DESC');
	}
	
	public function getQueryALoSumoNDeJugadorAnterioresALaFecha($id_jugador, \DateTime $fecha, $n = 12)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();

		$inicio = clone $fecha;
		$inicio->modify('-1 day -' . $n . ' month');
		
		return $this->getQueryActualizacionesJugadorOrderByVigenciaDesc($id_jugador)
				->andWhere('ja.vigencia BETWEEN :inicio AND :fin')
				->setParameter('inicio', $inicio)
				->setParameter('fin', $fecha)
				->setMaxResults($n)
				;
	}
	
	public function getALoSumoNAnterioresDeJugadorALaFecha($id_jugador, \DateTime $fecha, $n = 12)
	{
		return $this->getQueryALoSumoNDeJugadorAnterioresALaFecha($id_jugador, $fecha)->getQuery()->execute();
	}

}
