<?php

namespace Par3\GolfEnLaNubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ClassesWithParents\A;


/**
 * TemporadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemporadaRepository extends EntityRepository
{
	public function findTemporadaDeCircuitoEnFecha($id_circuito, \DateTime $fecha)
	{
		return $this ->createQueryBuilder('t')
					->where('t.id_circuito = :circuito')
					->andWhere('t.inicio <= :fecha')
					->andWhere('t.fin >= :fecha')
					->setParameter('fecha', $fecha)
					->setParameter('circuito', $id_circuito)
					->setMaxResults(1)
					->getQuery()
					->execute(); 
	}
	
	public function findTemporadaActualDeCircuito($id_circuito)
	{
		$rs = $this->findTemporadaDeCircuitoEnFecha($id_circuito, new \DateTime());
		return ($rs[0]);
	}
}
