<?php

namespace Par3\GolfEnLaNubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ClassesWithParents\A;
use Doctrine\Common\Util\Debug;

/**
 * TemporadaClubJugadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemporadaClubJugadorRepository extends EntityRepository
{
	public function getQueryBuilderListasDeBuenaFeDeTemporada($id_temporada)
	{
		return $this->getEntityManager()->createQueryBuilder()
					->select('tcj')
					->from('GolfEnLaNubeBundle:TemporadaClubJugador', 'tcj')
					->innerJoin('tcj.temporada_club', 'tc')
					->innerJoin('tc.club', 'c')
					->innerJoin('tcj.jugador', 'j')
					->innerJoin('j.persona', 'p')
					->where('tc.id_temporada = :id_temporada')
					->setParameter('id_temporada', $id_temporada)
					->orderBy('p.nombre_completo', 'ASC');

	}

	public function getQueryBuilderListasDeBuenaFeDeTemporadaYClubs($id_temporada, $clubs = array() )
	{
		$query = $this->getQueryBuilderListasDeBuenaFeDeTemporada($id_temporada); 
		if ( !empty($clubs) )
		{ 
			$query->andWhere($this->getEntityManager()->createQueryBuilder()->expr()->in('tc.id_club', $clubs));
		}
		return $query ; 
	}

	public function getQueryBuilderListasDeBuenaFeDeTemporadaYCapitan($id_temporada, User $usuario_capitan)
	{
		$clubs = array() ;
		foreach ($usuario_capitan->getCapitanTemporadaClubs() as $tc)
		{
			$clubs[] = $tc->getIdClub();
		}

		return $this->getQueryBuilderListasDeBuenaFeDeTemporadaYClubs($id_temporada, $clubs);
	}
}
