<?php

namespace Par3\GolfEnLaNubeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use ClassesWithParents\A;


/**
 * TemporadaClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemporadaClubRepository extends EntityRepository
{
	
	public function getQueryTemporadaClubsDeTemporada($id_temporada)
	{
		return $this->createQueryBuilder('tc')->where('tc.id_temporada = :temporada')->setParameter('temporada', $id_temporada);
	}
	
	public function findTemporadaClubsDeTemporadaOrderByNombreClubAsc($id_temporada)
	{
		return $this->getQueryTemporadaClubsDeTemporada($id_temporada)->innerJoin('tc.club', 'c')->orderBy('c.nombre', 'asc')->getQuery()->execute();
	}
	
	public function findTemporadaClubEnTemporadaDeCapitanParaChoices($id_temporada, $id_clubs = array())
	{
		$tcs = array();
		$qb = $this->createQueryBuilder('tc');
		$query = $qb ->select('tc')
			->where('tc.id_temporada = :temporada')->setParameter('temporada', $id_temporada);
		
		if (!empty($id_clubs))
		{
			$query->andWhere($qb->expr()->in('tc.id_club', $id_clubs));
		}
		
		$results = $query->getQuery()->getResult();
		
		foreach ($results as $tc) 
		{
			$tcs[$tc->getId()] = $tc->getClub()->getNombre();
		}

		return $tcs;
	}
}
