<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Temporada extends \Par3\GolfEnLaNubeBundle\Entity\Temporada implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdCircuito($idCircuito)
    {
        $this->__load();
        return parent::setIdCircuito($idCircuito);
    }

    public function getIdCircuito()
    {
        $this->__load();
        return parent::getIdCircuito();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setInicio($inicio)
    {
        $this->__load();
        return parent::setInicio($inicio);
    }

    public function getInicio()
    {
        $this->__load();
        return parent::getInicio();
    }

    public function setFin($fin)
    {
        $this->__load();
        return parent::setFin($fin);
    }

    public function getFin()
    {
        $this->__load();
        return parent::getFin();
    }

    public function setCircuito(\Par3\GolfEnLaNubeBundle\Entity\Circuito $circuito = NULL)
    {
        $this->__load();
        return parent::setCircuito($circuito);
    }

    public function getCircuito()
    {
        $this->__load();
        return parent::getCircuito();
    }

    public function addTemporadaClub(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClub $temporadaClubs)
    {
        $this->__load();
        return parent::addTemporadaClub($temporadaClubs);
    }

    public function removeTemporadaClub(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClub $temporadaClubs)
    {
        $this->__load();
        return parent::removeTemporadaClub($temporadaClubs);
    }

    public function getTemporadaClubs()
    {
        $this->__load();
        return parent::getTemporadaClubs();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'id_circuito', 'nombre', 'inicio', 'fin', 'circuito', 'temporada_clubs');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}