<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TemporadaClub extends \Par3\GolfEnLaNubeBundle\Entity\TemporadaClub implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function tieneJugadorConMatricula($matricula)
    {
        $this->__load();
        return parent::tieneJugadorConMatricula($matricula);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdTemporada($idTemporada)
    {
        $this->__load();
        return parent::setIdTemporada($idTemporada);
    }

    public function getIdTemporada()
    {
        $this->__load();
        return parent::getIdTemporada();
    }

    public function setIdClub($idClub)
    {
        $this->__load();
        return parent::setIdClub($idClub);
    }

    public function getIdClub()
    {
        $this->__load();
        return parent::getIdClub();
    }

    public function setClub(\Par3\GolfEnLaNubeBundle\Entity\Club $club = NULL)
    {
        $this->__load();
        return parent::setClub($club);
    }

    public function getClub()
    {
        $this->__load();
        return parent::getClub();
    }

    public function setTemporada(\Par3\GolfEnLaNubeBundle\Entity\Temporada $temporada = NULL)
    {
        $this->__load();
        return parent::setTemporada($temporada);
    }

    public function getTemporada()
    {
        $this->__load();
        return parent::getTemporada();
    }

    public function addJugadore(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClubJugador $jugadores)
    {
        $this->__load();
        return parent::addJugadore($jugadores);
    }

    public function removeJugadore(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClubJugador $jugadores)
    {
        $this->__load();
        return parent::removeJugadore($jugadores);
    }

    public function getJugadores()
    {
        $this->__load();
        return parent::getJugadores();
    }

    public function addClubJugadore(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClubJugador $clubJugadores)
    {
        $this->__load();
        return parent::addClubJugadore($clubJugadores);
    }

    public function removeClubJugadore(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClubJugador $clubJugadores)
    {
        $this->__load();
        return parent::removeClubJugadore($clubJugadores);
    }

    public function getClubJugadores()
    {
        $this->__load();
        return parent::getClubJugadores();
    }

    public function addCapitane(\Par3\GolfEnLaNubeBundle\Entity\User $capitanes)
    {
        $this->__load();
        return parent::addCapitane($capitanes);
    }

    public function removeCapitane(\Par3\GolfEnLaNubeBundle\Entity\User $capitanes)
    {
        $this->__load();
        return parent::removeCapitane($capitanes);
    }

    public function getCapitanes()
    {
        $this->__load();
        return parent::getCapitanes();
    }

    public function setEquipoIntraclub($equipoIntraclub)
    {
        $this->__load();
        return parent::setEquipoIntraclub($equipoIntraclub);
    }

    public function getEquipoIntraclub()
    {
        $this->__load();
        return parent::getEquipoIntraclub();
    }

    public function addEquipo(\Par3\GolfEnLaNubeBundle\Entity\Equipo $equipos)
    {
        $this->__load();
        return parent::addEquipo($equipos);
    }

    public function removeEquipo(\Par3\GolfEnLaNubeBundle\Entity\Equipo $equipos)
    {
        $this->__load();
        return parent::removeEquipo($equipos);
    }

    public function getEquipos()
    {
        $this->__load();
        return parent::getEquipos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'id_temporada', 'id_club', 'equipo_intraclub', 'club', 'temporada', 'club_jugadores', 'equipos', 'capitanes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}