<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TorneoFecha extends \Par3\GolfEnLaNubeBundle\Entity\TorneoFecha implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function limpiarPosicionesTorneoFechaJugadores()
    {
        $this->__load();
        return parent::limpiarPosicionesTorneoFechaJugadores();
    }

    public function limpiarPosicionesEquipos()
    {
        $this->__load();
        return parent::limpiarPosicionesEquipos();
    }

    public function limpiarPuntajesEquipos()
    {
        $this->__load();
        return parent::limpiarPuntajesEquipos();
    }

    public function tieneEquipoDeTemporadaClub(\Par3\GolfEnLaNubeBundle\Entity\TemporadaClub $tc)
    {
        $this->__load();
        return parent::tieneEquipoDeTemporadaClub($tc);
    }

    public function getTorneoFechaJugadorPorId($id)
    {
        $this->__load();
        return parent::getTorneoFechaJugadorPorId($id);
    }

    public function actualizarScoresPosicionesYPuntajes()
    {
        $this->__load();
        return parent::actualizarScoresPosicionesYPuntajes();
    }

    public function actualizarPuntajesEquipos()
    {
        $this->__load();
        return parent::actualizarPuntajesEquipos();
    }

    public function actualizarScoresTotalesJugadores()
    {
        $this->__load();
        return parent::actualizarScoresTotalesJugadores();
    }

    public function actualizarScoresTotalesEquipos()
    {
        $this->__load();
        return parent::actualizarScoresTotalesEquipos();
    }

    public function actualizarPosicionesEquipos()
    {
        $this->__load();
        return parent::actualizarPosicionesEquipos();
    }

    public function actualizarPosicionesJugadores()
    {
        $this->__load();
        return parent::actualizarPosicionesJugadores();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdTorneo($idTorneo)
    {
        $this->__load();
        return parent::setIdTorneo($idTorneo);
    }

    public function getIdTorneo()
    {
        $this->__load();
        return parent::getIdTorneo();
    }

    public function setIdCancha($idCancha)
    {
        $this->__load();
        return parent::setIdCancha($idCancha);
    }

    public function getIdCancha()
    {
        $this->__load();
        return parent::getIdCancha();
    }

    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }

    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }

    public function setCategoriasMasculinas($categoriasMasculinas)
    {
        $this->__load();
        return parent::setCategoriasMasculinas($categoriasMasculinas);
    }

    public function getCategoriasMasculinas()
    {
        $this->__load();
        return parent::getCategoriasMasculinas();
    }

    public function setCategoriasFemeninas($categoriasFemeninas)
    {
        $this->__load();
        return parent::setCategoriasFemeninas($categoriasFemeninas);
    }

    public function getCategoriasFemeninas()
    {
        $this->__load();
        return parent::getCategoriasFemeninas();
    }

    public function setJugadoresPorLinea($jugadoresPorLinea)
    {
        $this->__load();
        return parent::setJugadoresPorLinea($jugadoresPorLinea);
    }

    public function getJugadoresPorLinea()
    {
        $this->__load();
        return parent::getJugadoresPorLinea();
    }

    public function setSalidasSimultaneas($salidasSimultaneas)
    {
        $this->__load();
        return parent::setSalidasSimultaneas($salidasSimultaneas);
    }

    public function getSalidasSimultaneas()
    {
        $this->__load();
        return parent::getSalidasSimultaneas();
    }

    public function setUltimaSalida($ultimaSalida)
    {
        $this->__load();
        return parent::setUltimaSalida($ultimaSalida);
    }

    public function getUltimaSalida()
    {
        $this->__load();
        return parent::getUltimaSalida();
    }

    public function setFrecuenciaSalida($frecuenciaSalida)
    {
        $this->__load();
        return parent::setFrecuenciaSalida($frecuenciaSalida);
    }

    public function getFrecuenciaSalida()
    {
        $this->__load();
        return parent::getFrecuenciaSalida();
    }

    public function setSuspendido($suspendido)
    {
        $this->__load();
        return parent::setSuspendido($suspendido);
    }

    public function getSuspendido()
    {
        $this->__load();
        return parent::getSuspendido();
    }

    public function setTorneo(\Par3\GolfEnLaNubeBundle\Entity\Torneo $torneo = NULL)
    {
        $this->__load();
        return parent::setTorneo($torneo);
    }

    public function getTorneo()
    {
        $this->__load();
        return parent::getTorneo();
    }

    public function setCancha(\Par3\GolfEnLaNubeBundle\Entity\Cancha $cancha = NULL)
    {
        $this->__load();
        return parent::setCancha($cancha);
    }

    public function getCancha()
    {
        $this->__load();
        return parent::getCancha();
    }

    public function addCategoria(\Par3\GolfEnLaNubeBundle\Entity\TorneoFechaCategoria $categorias)
    {
        $this->__load();
        return parent::addCategoria($categorias);
    }

    public function removeCategoria(\Par3\GolfEnLaNubeBundle\Entity\TorneoFechaCategoria $categorias)
    {
        $this->__load();
        return parent::removeCategoria($categorias);
    }

    public function getCategorias()
    {
        $this->__load();
        return parent::getCategorias();
    }

    public function addTorneoFechaJugadore(\Par3\GolfEnLaNubeBundle\Entity\TorneoFechaJugador $torneoFechaJugadores)
    {
        $this->__load();
        return parent::addTorneoFechaJugadore($torneoFechaJugadores);
    }

    public function removeTorneoFechaJugadore(\Par3\GolfEnLaNubeBundle\Entity\TorneoFechaJugador $torneoFechaJugadores)
    {
        $this->__load();
        return parent::removeTorneoFechaJugadore($torneoFechaJugadores);
    }

    public function getTorneoFechaJugadores()
    {
        $this->__load();
        return parent::getTorneoFechaJugadores();
    }

    public function getTorneoFechaJugadoresConTarjeta()
    {
        $this->__load();
        return parent::getTorneoFechaJugadoresConTarjeta();
    }

    public function addEquipo(\Par3\GolfEnLaNubeBundle\Entity\Equipo $equipos)
    {
        $this->__load();
        return parent::addEquipo($equipos);
    }

    public function removeEquipo(\Par3\GolfEnLaNubeBundle\Entity\Equipo $equipos)
    {
        $this->__load();
        return parent::removeEquipo($equipos);
    }

    public function getEquipos()
    {
        $this->__load();
        return parent::getEquipos();
    }

    public function getEquiposOrderByPosicion()
    {
        $this->__load();
        return parent::getEquiposOrderByPosicion();
    }

    public function getEquiposOrderByPuntosPorPosicion()
    {
        $this->__load();
        return parent::getEquiposOrderByPuntosPorPosicion();
    }

    public function getEquiposOrderByPuntosPorPuntajeTotal()
    {
        $this->__load();
        return parent::getEquiposOrderByPuntosPorPuntajeTotal();
    }

    public function setConcluido($concluido)
    {
        $this->__load();
        return parent::setConcluido($concluido);
    }

    public function getConcluido()
    {
        $this->__load();
        return parent::getConcluido();
    }

    public function setHoyos($hoyos)
    {
        $this->__load();
        return parent::setHoyos($hoyos);
    }

    public function getHoyos()
    {
        $this->__load();
        return parent::getHoyos();
    }

    public function setHabilitarCargaResultados($habilitarCargaResultados)
    {
        $this->__load();
        return parent::setHabilitarCargaResultados($habilitarCargaResultados);
    }

    public function getHabilitarCargaResultados()
    {
        $this->__load();
        return parent::getHabilitarCargaResultados();
    }

    public function setNumeroFecha($numeroFecha)
    {
        $this->__load();
        return parent::setNumeroFecha($numeroFecha);
    }

    public function getNumeroFecha()
    {
        $this->__load();
        return parent::getNumeroFecha();
    }

    public function setAperturaInscripcion($aperturaInscripcion)
    {
        $this->__load();
        return parent::setAperturaInscripcion($aperturaInscripcion);
    }

    public function getAperturaInscripcion()
    {
        $this->__load();
        return parent::getAperturaInscripcion();
    }

    public function setCierreInscripcion($cierreInscripcion)
    {
        $this->__load();
        return parent::setCierreInscripcion($cierreInscripcion);
    }

    public function getCierreInscripcion()
    {
        $this->__load();
        return parent::getCierreInscripcion();
    }

    public function setAperturaInscripcionNoSocios($aperturaInscripcionNoSocios)
    {
        $this->__load();
        return parent::setAperturaInscripcionNoSocios($aperturaInscripcionNoSocios);
    }

    public function getAperturaInscripcionNoSocios()
    {
        $this->__load();
        return parent::getAperturaInscripcionNoSocios();
    }

    public function setCierreInscripcionNoSocios($cierreInscripcionNoSocios)
    {
        $this->__load();
        return parent::setCierreInscripcionNoSocios($cierreInscripcionNoSocios);
    }

    public function getCierreInscripcionNoSocios()
    {
        $this->__load();
        return parent::getCierreInscripcionNoSocios();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'id_torneo', 'id_cancha', 'numero_fecha', 'apertura_inscripcion', 'cierre_inscripcion', 'apertura_inscripcion_no_socios', 'cierre_inscripcion_no_socios', 'fecha', 'hoyos', 'categorias_masculinas', 'categorias_femeninas', 'jugadores_por_linea', 'salidas_simultaneas', 'ultima_salida', 'frecuencia_salida', 'concluido', 'habilitar_carga_resultados', 'suspendido', 'torneo', 'cancha', 'categorias', 'equipos', 'torneo_fecha_jugadores');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}