<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class JugadorActualizacion extends \Par3\GolfEnLaNubeBundle\Entity\JugadorActualizacion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function vigenciaHasta()
    {
        $this->__load();
        return parent::vigenciaHasta();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdJugador($idJugador)
    {
        $this->__load();
        return parent::setIdJugador($idJugador);
    }

    public function getIdJugador()
    {
        $this->__load();
        return parent::getIdJugador();
    }

    public function setVigencia($vigencia)
    {
        $this->__load();
        return parent::setVigencia($vigencia);
    }

    public function getVigencia()
    {
        $this->__load();
        return parent::getVigencia();
    }

    public function setHandicapEstandar($handicapEstandar)
    {
        $this->__load();
        return parent::setHandicapEstandar($handicapEstandar);
    }

    public function getHandicapEstandar()
    {
        $this->__load();
        return parent::getHandicapEstandar();
    }

    public function setHandicapPar3($handicapPar3)
    {
        $this->__load();
        return parent::setHandicapPar3($handicapPar3);
    }

    public function getHandicapPar3()
    {
        $this->__load();
        return parent::getHandicapPar3();
    }

    public function setTarjetasEstandar($tarjetasEstandar)
    {
        $this->__load();
        return parent::setTarjetasEstandar($tarjetasEstandar);
    }

    public function getTarjetasEstandar()
    {
        $this->__load();
        return parent::getTarjetasEstandar();
    }

    public function setTarjetasPar3($tarjetasPar3)
    {
        $this->__load();
        return parent::setTarjetasPar3($tarjetasPar3);
    }

    public function getTarjetasPar3()
    {
        $this->__load();
        return parent::getTarjetasPar3();
    }

    public function setJugador(\Par3\GolfEnLaNubeBundle\Entity\Jugador $jugador = NULL)
    {
        $this->__load();
        return parent::setJugador($jugador);
    }

    public function getJugador()
    {
        $this->__load();
        return parent::getJugador();
    }

    public function setIdClubOpcion($idClubOpcion)
    {
        $this->__load();
        return parent::setIdClubOpcion($idClubOpcion);
    }

    public function getIdClubOpcion()
    {
        $this->__load();
        return parent::getIdClubOpcion();
    }

    public function setClubOpcion(\Par3\GolfEnLaNubeBundle\Entity\Club $clubOpcion = NULL)
    {
        $this->__load();
        return parent::setClubOpcion($clubOpcion);
    }

    public function getClubOpcion()
    {
        $this->__load();
        return parent::getClubOpcion();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'id_jugador', 'id_club_opcion', 'vigencia', 'handicap_estandar', 'handicap_par3', 'tarjetas_estandar', 'tarjetas_par3', 'jugador', 'club_opcion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}