<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Torneo extends \Par3\GolfEnLaNubeBundle\Entity\Torneo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setInicio($inicio)
    {
        $this->__load();
        return parent::setInicio($inicio);
    }

    public function getInicio()
    {
        $this->__load();
        return parent::getInicio();
    }

    public function setIdInstitucion($idInstitucion)
    {
        $this->__load();
        return parent::setIdInstitucion($idInstitucion);
    }

    public function getIdInstitucion()
    {
        $this->__load();
        return parent::getIdInstitucion();
    }

    public function setDias($dias)
    {
        $this->__load();
        return parent::setDias($dias);
    }

    public function getDias()
    {
        $this->__load();
        return parent::getDias();
    }

    public function setIdFormatoJuego($idFormatoJuego)
    {
        $this->__load();
        return parent::setIdFormatoJuego($idFormatoJuego);
    }

    public function getIdFormatoJuego()
    {
        $this->__load();
        return parent::getIdFormatoJuego();
    }

    public function setSeparaSexos($separaSexos)
    {
        $this->__load();
        return parent::setSeparaSexos($separaSexos);
    }

    public function getSeparaSexos()
    {
        $this->__load();
        return parent::getSeparaSexos();
    }

    public function setAperturaInscripcion($aperturaInscripcion)
    {
        $this->__load();
        return parent::setAperturaInscripcion($aperturaInscripcion);
    }

    public function getAperturaInscripcion()
    {
        $this->__load();
        return parent::getAperturaInscripcion();
    }

    public function setCierreInscripcion($cierreInscripcion)
    {
        $this->__load();
        return parent::setCierreInscripcion($cierreInscripcion);
    }

    public function getCierreInscripcion()
    {
        $this->__load();
        return parent::getCierreInscripcion();
    }

    public function setAperturaInscripcionNoSocios($aperturaInscripcionNoSocios)
    {
        $this->__load();
        return parent::setAperturaInscripcionNoSocios($aperturaInscripcionNoSocios);
    }

    public function getAperturaInscripcionNoSocios()
    {
        $this->__load();
        return parent::getAperturaInscripcionNoSocios();
    }

    public function setCierreInscripcionNoSocios($cierreInscripcionNoSocios)
    {
        $this->__load();
        return parent::setCierreInscripcionNoSocios($cierreInscripcionNoSocios);
    }

    public function getCierreInscripcionNoSocios()
    {
        $this->__load();
        return parent::getCierreInscripcionNoSocios();
    }

    public function setTipoTorneo($tipoTorneo)
    {
        $this->__load();
        return parent::setTipoTorneo($tipoTorneo);
    }

    public function getTipoTorneo()
    {
        $this->__load();
        return parent::getTipoTorneo();
    }

    public function setSaMaxInvitados($saMaxInvitados)
    {
        $this->__load();
        return parent::setSaMaxInvitados($saMaxInvitados);
    }

    public function getSaMaxInvitados()
    {
        $this->__load();
        return parent::getSaMaxInvitados();
    }

    public function setSaInvitadosMismaLinea($saInvitadosMismaLinea)
    {
        $this->__load();
        return parent::setSaInvitadosMismaLinea($saInvitadosMismaLinea);
    }

    public function getSaInvitadosMismaLinea()
    {
        $this->__load();
        return parent::getSaInvitadosMismaLinea();
    }

    public function setAbPublicaEnGolfplay($abPublicaEnGolfplay)
    {
        $this->__load();
        return parent::setAbPublicaEnGolfplay($abPublicaEnGolfplay);
    }

    public function getAbPublicaEnGolfplay()
    {
        $this->__load();
        return parent::getAbPublicaEnGolfplay();
    }

    public function setIncluirEnRanking($incluirEnRanking)
    {
        $this->__load();
        return parent::setIncluirEnRanking($incluirEnRanking);
    }

    public function getIncluirEnRanking()
    {
        $this->__load();
        return parent::getIncluirEnRanking();
    }

    public function setTitularesPorClub($titularesPorClub)
    {
        $this->__load();
        return parent::setTitularesPorClub($titularesPorClub);
    }

    public function getTitularesPorClub()
    {
        $this->__load();
        return parent::getTitularesPorClub();
    }

    public function setSuplentesPorClub($suplentesPorClub)
    {
        $this->__load();
        return parent::setSuplentesPorClub($suplentesPorClub);
    }

    public function getSuplentesPorClub()
    {
        $this->__load();
        return parent::getSuplentesPorClub();
    }

    public function setInstitucion(\Par3\GolfEnLaNubeBundle\Entity\Institucion $institucion = NULL)
    {
        $this->__load();
        return parent::setInstitucion($institucion);
    }

    public function getInstitucion()
    {
        $this->__load();
        return parent::getInstitucion();
    }

    public function setFormatoJuego(\Par3\GolfEnLaNubeBundle\Entity\FormatoJuego $formatoJuego = NULL)
    {
        $this->__load();
        return parent::setFormatoJuego($formatoJuego);
    }

    public function getFormatoJuego()
    {
        $this->__load();
        return parent::getFormatoJuego();
    }

    public function addFecha(\Par3\GolfEnLaNubeBundle\Entity\TorneoFecha $fechas)
    {
        $this->__load();
        return parent::addFecha($fechas);
    }

    public function removeFecha(\Par3\GolfEnLaNubeBundle\Entity\TorneoFecha $fechas)
    {
        $this->__load();
        return parent::removeFecha($fechas);
    }

    public function getFechas()
    {
        $this->__load();
        return parent::getFechas();
    }

    public function setIdCircuito($idCircuito)
    {
        $this->__load();
        return parent::setIdCircuito($idCircuito);
    }

    public function getIdCircuito()
    {
        $this->__load();
        return parent::getIdCircuito();
    }

    public function setIdTemporada($idTemporada)
    {
        $this->__load();
        return parent::setIdTemporada($idTemporada);
    }

    public function getIdTemporada()
    {
        $this->__load();
        return parent::getIdTemporada();
    }

    public function setTemporada(\Par3\GolfEnLaNubeBundle\Entity\Temporada $temporada = NULL)
    {
        $this->__load();
        return parent::setTemporada($temporada);
    }

    public function getTemporada()
    {
        $this->__load();
        return parent::getTemporada();
    }

    public function addCampeonato(\Par3\GolfEnLaNubeBundle\Entity\Campeonato $campeonatos)
    {
        $this->__load();
        return parent::addCampeonato($campeonatos);
    }

    public function removeCampeonato(\Par3\GolfEnLaNubeBundle\Entity\Campeonato $campeonatos)
    {
        $this->__load();
        return parent::removeCampeonato($campeonatos);
    }

    public function getCampeonatos()
    {
        $this->__load();
        return parent::getCampeonatos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'inicio', 'id_institucion', 'id_temporada', 'dias', 'id_formato_juego', 'separa_sexos', 'apertura_inscripcion', 'cierre_inscripcion', 'apertura_inscripcion_no_socios', 'cierre_inscripcion_no_socios', 'tipo_torneo', 'sa_max_invitados', 'sa_invitados_misma_linea', 'ab_publica_en_golfplay', 'incluir_en_ranking', 'titulares_por_club', 'suplentes_por_club', 'institucion', 'campeonatos', 'temporada', 'formato_juego', 'fechas');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}