<?php

namespace Proxies\__CG__\Par3\GolfEnLaNubeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TorneoFechaJugador extends \Par3\GolfEnLaNubeBundle\Entity\TorneoFechaJugador implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIdTorneoFecha($idTorneoFecha)
    {
        $this->__load();
        return parent::setIdTorneoFecha($idTorneoFecha);
    }

    public function getIdTorneoFecha()
    {
        $this->__load();
        return parent::getIdTorneoFecha();
    }

    public function setIdJugador($idJugador)
    {
        $this->__load();
        return parent::setIdJugador($idJugador);
    }

    public function getIdJugador()
    {
        $this->__load();
        return parent::getIdJugador();
    }

    public function setIdEquipo($idEquipo)
    {
        $this->__load();
        return parent::setIdEquipo($idEquipo);
    }

    public function getIdEquipo()
    {
        $this->__load();
        return parent::getIdEquipo();
    }

    public function setCapitanEquipo($capitanEquipo)
    {
        $this->__load();
        return parent::setCapitanEquipo($capitanEquipo);
    }

    public function getCapitanEquipo()
    {
        $this->__load();
        return parent::getCapitanEquipo();
    }

    public function setTitular($titular)
    {
        $this->__load();
        return parent::setTitular($titular);
    }

    public function getTitular()
    {
        $this->__load();
        return parent::getTitular();
    }

    public function setIdClub($idClub)
    {
        $this->__load();
        return parent::setIdClub($idClub);
    }

    public function getIdClub()
    {
        $this->__load();
        return parent::getIdClub();
    }

    public function setHandicapPar3($handicapPar3)
    {
        $this->__load();
        return parent::setHandicapPar3($handicapPar3);
    }

    public function getHandicapPar3()
    {
        $this->__load();
        return parent::getHandicapPar3();
    }

    public function setHandicapEstandar($handicapEstandar)
    {
        $this->__load();
        return parent::setHandicapEstandar($handicapEstandar);
    }

    public function getHandicapEstandar()
    {
        $this->__load();
        return parent::getHandicapEstandar();
    }

    public function setTorneoFecha(\Par3\GolfEnLaNubeBundle\Entity\TorneoFecha $torneoFecha = NULL)
    {
        $this->__load();
        return parent::setTorneoFecha($torneoFecha);
    }

    public function getTorneoFecha()
    {
        $this->__load();
        return parent::getTorneoFecha();
    }

    public function setJugador(\Par3\GolfEnLaNubeBundle\Entity\Jugador $jugador = NULL)
    {
        $this->__load();
        return parent::setJugador($jugador);
    }

    public function getJugador()
    {
        $this->__load();
        return parent::getJugador();
    }

    public function setEquipo(\Par3\GolfEnLaNubeBundle\Entity\Equipo $equipo = NULL)
    {
        $this->__load();
        return parent::setEquipo($equipo);
    }

    public function getEquipo()
    {
        $this->__load();
        return parent::getEquipo();
    }

    public function setClub(\Par3\GolfEnLaNubeBundle\Entity\Club $club = NULL)
    {
        $this->__load();
        return parent::setClub($club);
    }

    public function getClub()
    {
        $this->__load();
        return parent::getClub();
    }

    public function setHandicapDeJuego($handicapDeJuego)
    {
        $this->__load();
        return parent::setHandicapDeJuego($handicapDeJuego);
    }

    public function getHandicapDeJuego()
    {
        $this->__load();
        return parent::getHandicapDeJuego();
    }

    public function setTarjeta(\Par3\GolfEnLaNubeBundle\Entity\Tarjeta $tarjeta = NULL)
    {
        $this->__load();
        return parent::setTarjeta($tarjeta);
    }

    public function getTarjeta()
    {
        $this->__load();
        return parent::getTarjeta();
    }

    public function setPosicionPorNeto($posicionPorNeto)
    {
        $this->__load();
        return parent::setPosicionPorNeto($posicionPorNeto);
    }

    public function getPosicionPorNeto()
    {
        $this->__load();
        return parent::getPosicionPorNeto();
    }

    public function setPosicionPorGross($posicionPorGross)
    {
        $this->__load();
        return parent::setPosicionPorGross($posicionPorGross);
    }

    public function getPosicionPorGross()
    {
        $this->__load();
        return parent::getPosicionPorGross();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'id_torneo_fecha', 'id_jugador', 'id_equipo', 'capitan_equipo', 'titular', 'id_club', 'handicap_par3', 'handicap_estandar', 'handicap_de_juego', 'posicion_por_neto', 'posicion_por_gross', 'torneo_fecha', 'jugador', 'equipo', 'club', 'tarjeta');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}