admin_equipo:
    pattern:  /
    defaults: { _controller: "GolfEnLaNubeBundle:Equipo:index" }

admin_equipo_show:
    pattern:  /{id}/show
    defaults: { _controller: "GolfEnLaNubeBundle:Equipo:show" }

admin_equipo_new:
    pattern:  /new/torneofecha/{id_torneo_fecha}/club/{id_club}
    defaults: { _controller: "GolfEnLaNubeBundle:Equipo:new" }

admin_equipo_create:
    pattern:  /create
    defaults: { _controller: "GolfEnLaNubeBundle:Equipo:create" }
    requirements: { _method: post }

admin_equipo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GolfEnLaNubeBundle:Equipo:edit" }

admin_equipo_update:
    pattern:  /{id}/update
    defaults: { _controller: "GolfEnLaNubeBundle:Equipo:update" }
    requirements: { _method: post|put }

admin_equipo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GolfEnLaNubeBundle:Equipo:delete" }
    requirements: { _method: post|delete }
