admin_institucion:
    pattern:  /
    defaults: { _controller: "GolfEnLaNubeBundle:Institucion:index" }

admin_institucion_show:
    pattern:  /{id}/show
    defaults: { _controller: "GolfEnLaNubeBundle:Institucion:show" }

admin_institucion_new:
    pattern:  /new
    defaults: { _controller: "GolfEnLaNubeBundle:Institucion:new" }

admin_institucion_create:
    pattern:  /create
    defaults: { _controller: "GolfEnLaNubeBundle:Institucion:create" }
    requirements: { _method: post }

admin_institucion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GolfEnLaNubeBundle:Institucion:edit" }

admin_institucion_update:
    pattern:  /{id}/update
    defaults: { _controller: "GolfEnLaNubeBundle:Institucion:update" }
    requirements: { _method: post|put }

admin_institucion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GolfEnLaNubeBundle:Institucion:delete" }
    requirements: { _method: post|delete }
