admin_user:
    pattern:  /
    defaults: { _controller: "GolfEnLaNubeBundle:User:index" }

admin_user_show:
    pattern:  /{id}/show
    defaults: { _controller: "GolfEnLaNubeBundle:User:show" }

admin_user_new:
    pattern:  /new
    defaults: { _controller: "GolfEnLaNubeBundle:User:new" }

admin_user_create:
    pattern:  /create
    defaults: { _controller: "GolfEnLaNubeBundle:User:create" }
    requirements: { _method: post }

admin_user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GolfEnLaNubeBundle:User:edit" }

admin_user_update:
    pattern:  /{id}/update
    defaults: { _controller: "GolfEnLaNubeBundle:User:update" }
    requirements: { _method: post|put }

admin_user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GolfEnLaNubeBundle:User:delete" }
    requirements: { _method: post|delete }

admin_user_elegir_perfiles:
    pattern: /{id}/elegirPerfiles
    defaults: { _controller: "GolfEnLaNubeBundle:User:elegirPerfiles" }

admin_user_asignar_perfiles:
    pattern: /asignarPerfiles
    defaults: { _controller: "GolfEnLaNubeBundle:User:asignarPerfiles" }
